name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 16
        cache: pnpm
    - run: pnpm install --frozen-lockfile
    - run: pnpm run lint

  test:
    name: "test with eslint ${{ matrix.eslint-version}} on node v${{ matrix.node-version }}"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        eslint-version:
          - 7
          - 8
        node-version:
          - 14
          - 16
          - 18

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: pnpm
    - run: pnpm i --frozen-lockfile
    - run: pnpm i eslint@${{ matrix.eslint-version }}
    - run: pnpm test
